version: '3.7'

services:
  qdrant:
    container_name: index-db
    image: qdrant/qdrant:latest
    ports:
      - "6550:6333"  # REST API (host:container)
      - "6551:6334"  # GRPC API (host:container)
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    restart: unless-stopped

volumes:
  qdrant_storage:
    name: index-db-storage 