services:
  qdrant:
    container_name: index-db
    image: qdrant/qdrant:latest
    platform: linux/amd64
    ports:
      - "6550:6333"  # REST API (host:container)
      - "6551:6334"  # GRPC API (host:container)
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  qdrant_storage:
    name: index-db-storage